### ISSUE TITLE
How can I update this to FreeRADIUS Version 3.2.3

### ISSUE THREAD

**Issue by bertybuttface** [oviserv/wifi_eap_tls#2]
I see that there are some patches here, I'm guessing it isn't as simple as bumping a version number. Can a Github Action help?

**Comment by oviserv** [comment]
Alpine Linux doesn't have a FreeRadius package yet, so this requires quite a lot of work:
- Compile FreeRADIUS 3.2.3 from source
- Analyze the difference between FreeRADIUS config files for version 3.0.26 and 3.2.3 and regenerate the config patches
- Maybe convert between old and new config
- Test the whole setup

As the 3.0.x branch is still supported, there are currently no plans to switch to 3.2.x. What is your specific use case for FreeRADIUS 3.2.3?

**Comment by bertybuttface** [comment]
Thanks for the quick reply.I have no need for any additional features outside of security updates.I’m guessing ongoing 3.0.x updates are easier because no config changes?On 22 Nov 2023, at 17:34, oviserv ***@***.***> wrote:﻿
Alpine Linux doesn't have a FreeRadius package yet, so this requires quite a lot of work:

Compile FreeRADIUS 3.2.3 from source
Analyze the difference between FreeRADIUS config files for version 3.0.26 and 3.2.3 and regenerate the config patches
Maybe convert between old and new config
Test the whole setup

As the 3.0.x branch is still supported, there are currently no plans to switch to 3.2.x. What is your specific use case for FreeRADIUS 3.2.3?

**Comment by oviserv** [comment]
Updating within the 3.0.x branch is much easier indeed. As both Alpine 3.17 and FreeRADIUS 3.0.x are still supported security updates should be fine.
